import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Header } from "@/components/layout/header";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { AuthProvider } from "@/components/providers/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ErrorBoundary } from "@/components/ui/error-boundary";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "min-h-screen bg-background font-sans antialiased")}>
        <AuthProvider>
          <NuqsAdapter>
            <Header />
            <ErrorBoundary name="GlobalLayout">
              <main>{children}</main>
            </ErrorBoundary>
            <Toaster />
            <Sonner position="top-right" expand={true} richColors />
          </NuqsAdapter>
        </AuthProvider>
      </body>
    </html>
  );
}
